### ISSUE TITLE
ModuleNotFoundError: No module named 'compile.py'; 'compile' is not a package

### ISSUE THREAD

**Issue by virpatel524** [algorand-devrel/pyteal-course#6]
Hi, 

I'm trying to run the following command starting the tutorial: **bash build.sh compile.py contracts.counter.step_01**. 

When I run this command, I quickly run into an error: **_ModuleNotFoundError: No module named 'compile.py'; 'compile' is not a package_**

I'm completely lost as to what's happening here. Any support would be greatly appreciated.

**Comment by s-monfared** [comment]
Hi,

I'm having a similar issue with running the "./build.sh contracts/counter/step_01" command. Did you find any solution?

This is what I get:

Traceback (most recent call last):
  File "./compile.py", line 19, in <module>
    contract = importlib.import_module(mod)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'contracts/counter/step_01'

Thanks
